#!/bin/sh

# Script for installation of PRISM on a clean install of Ubuntu

set -e # Abort if one of the commands fail
set -x # Print commands as they are executed

# Install dependencies: make/gcc/Java/git
sudo apt-get -y update
sudo apt -y install make gcc g++ default-jdk git

# Install Python (only needed for testing (prism-auto) currently)
sudo apt -y install python

# Download the version for QComp 2019 from GitHub
git clone https://github.com/prismmodelchecker/prism-ext.git -b qcomp19-final prism.git

# Compile PRISM and run a single test
# (should ultimately display: "Testing result: PASS")
(cd prism.git/prism && make && make test)

# qcomp 2019 specific: generate symlinks to fix-syntax and the prism startup script
ln -s prism.git/prism/etc/scripts/qcomp19-fix-syntax ./fix-syntax
ln -s prism.git/prism/bin/prism ./prism
